### ISSUE TITLE
Crash if query doesn't return a table

### ISSUE THREAD

**Issue by R0flcopt3r** [barskern/pandoc-filter-runsql#1]
Tried with the following queries:

```sql
~~~ runsql
DELETE FROM training_session
WHERE training_session.athlete_id = (SELECT athlete.id FROM athlete WHERE athlete.name = 'Per Persen' )
;
~~~
```
```sql
~~~ runsql
DELETE FROM training_session
WHERE training_session.athlete_id = (SELECT athlete.id FROM athlete WHERE athlete.name = 'Per Persen' )
;
~~~
```

Both returns the following traceback:
```
Traceback (most recent call last):
  File "./runsql.py", line 59, in <module>
    run_filter(yaml_filter, tag="runsql", function=action)
  File "/usr/local/lib/python3.7/site-packages/panflute/io.py", line 260, in run_filter
    return run_filters([action], *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/panflute/io.py", line 241, in run_filters
    doc = doc.walk(action, doc)
  File "/usr/local/lib/python3.7/site-packages/panflute/base.py", line 273, in walk
    ans = list(chain.from_iterable(ans))
  File "/usr/local/lib/python3.7/site-packages/panflute/base.py", line 271, in <genexpr>
    ans = ((item,) if type(item) != list else item for item in ans)
  File "/usr/local/lib/python3.7/site-packages/panflute/base.py", line 268, in <genexpr>
    ans = (item.walk(action, doc) for item in obj)
  File "/usr/local/lib/python3.7/site-packages/panflute/base.py", line 284, in walk
    altered = action(self, doc)
  File "/usr/local/lib/python3.7/site-packages/panflute/tools.py", line 158, in yaml_filter
    element=element, doc=doc)
  File "./runsql.py", line 47, in action
    column_names = TableRow(*[TableCell(Plain(Str(i[0]))) for i in cur.description])
TypeError: 'NoneType' object is not iterable
Error running filter runsql.py:
Filter returned error status 1
```

Testing with a query that returns a table, everything works as expected.

**Comment by barskern** [comment]
Queries that don't produce a result (in the form of rows) need to have the special option `no_result` Specified. This is not yet documented so a PR is welcome. 😊

```
~~~ runsql
no_result: True
---
INSERT INTO athlete (id, email, name, gender, year_of_birth, min_heart_rate, max_heart_rate, club_code) 
VALUES (8, 'ryan00@realmail.no', 'Ryan Ishus', 'Male' , 2000, NULL, NULL, 'lillehammerif' )
;
~~~
```
